---
name: Date-Holidays-USFederal
version: 0.01
author: []
abstract: Determine US Federal Public Holidays
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  perl: 5.006
build_requires:
  Test::More: 0
provides:
  Date::Holidays::USFederal:
    file: lib/Date/Holidays/USFederal.pm
    version: 0.01
generated_by: Module::Build version 0.2805
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
